fix(ci): remove musl and alpine build dependency on cli build

diff --git a/.github/actions/test-cli/action.yml b/.github/actions/test-cli/action.yml
--- a/.github/actions/test-cli/action.yml
+++ b/.github/actions/test-cli/action.yml
@@ -13,10 +13,10 @@ runs:
       shell: sh
       run: |
         check() {
-          if [[ "$1" != *"$2"* ]]; then
-            echo "check failed: '$1' should contain '$2'"
-            exit 1
-          fi
+          case "$1" in
+            *"$2"*) ;;  # match is fine
+            *) echo "check failed: '$1' should contain '$2'"; exit 1 ;;
+          esac
         }
 
         chmod +x ./jstz
